# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\browsers_dialogs\chrome_preview_dialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ChromePreviewDialog(object):
    def setupUi(self, ChromePreviewDialog):
        ChromePreviewDialog.setObjectName(_fromUtf8("ChromePreviewDialog"))
        ChromePreviewDialog.resize(600, 375)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ChromePreviewDialog.sizePolicy().hasHeightForWidth())
        ChromePreviewDialog.setSizePolicy(sizePolicy)
        ChromePreviewDialog.setMinimumSize(QtCore.QSize(600, 375))
        ChromePreviewDialog.setMaximumSize(QtCore.QSize(600, 375))
        self.gridLayout_3 = QtGui.QGridLayout(ChromePreviewDialog)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(ChromePreviewDialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ebrima"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.line_dialog_title = QtGui.QLineEdit(ChromePreviewDialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ebrima"))
        font.setPointSize(12)
        self.line_dialog_title.setFont(font)
        self.line_dialog_title.setObjectName(_fromUtf8("line_dialog_title"))
        self.gridLayout.addWidget(self.line_dialog_title, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.button_close_dialog = QtGui.QPushButton(ChromePreviewDialog)
        self.button_close_dialog.setMinimumSize(QtCore.QSize(24, 24))
        self.button_close_dialog.setMaximumSize(QtCore.QSize(24, 24))
        self.button_close_dialog.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/button_close.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_close_dialog.setIcon(icon)
        self.button_close_dialog.setIconSize(QtCore.QSize(24, 24))
        self.button_close_dialog.setObjectName(_fromUtf8("button_close_dialog"))
        self.gridLayout.addWidget(self.button_close_dialog, 0, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_8 = QtGui.QLabel(ChromePreviewDialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ebrima"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 5, 0, 1, 1)
        self.line_creation_time = QtGui.QLineEdit(ChromePreviewDialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ebrima"))
        font.setPointSize(9)
        self.line_creation_time.setFont(font)
        self.line_creation_time.setObjectName(_fromUtf8("line_creation_time"))
        self.gridLayout_2.addWidget(self.line_creation_time, 5, 1, 1, 1)
        self.line_refetch_count = QtGui.QLineEdit(ChromePreviewDialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ebrima"))
        font.setPointSize(9)
        self.line_refetch_count.setFont(font)
        self.line_refetch_count.setObjectName(_fromUtf8("line_refetch_count"))
        self.gridLayout_2.addWidget(self.line_refetch_count, 3, 1, 1, 1)
        self.label_9 = QtGui.QLabel(ChromePreviewDialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ebrima"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 6, 0, 1, 1)
        self.line_reuse_count = QtGui.QLineEdit(ChromePreviewDialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ebrima"))
        font.setPointSize(9)
        self.line_reuse_count.setFont(font)
        self.line_reuse_count.setObjectName(_fromUtf8("line_reuse_count"))
        self.gridLayout_2.addWidget(self.line_reuse_count, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(ChromePreviewDialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ebrima"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(ChromePreviewDialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ebrima"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.line_key_hash = QtGui.QLineEdit(ChromePreviewDialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ebrima"))
        font.setPointSize(9)
        self.line_key_hash.setFont(font)
        self.line_key_hash.setObjectName(_fromUtf8("line_key_hash"))
        self.gridLayout_2.addWidget(self.line_key_hash, 0, 1, 1, 1)
        self.line_key_data_size = QtGui.QLineEdit(ChromePreviewDialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ebrima"))
        font.setPointSize(9)
        self.line_key_data_size.setFont(font)
        self.line_key_data_size.setObjectName(_fromUtf8("line_key_data_size"))
        self.gridLayout_2.addWidget(self.line_key_data_size, 6, 1, 1, 1)
        self.label_11 = QtGui.QLabel(ChromePreviewDialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ebrima"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 8, 0, 1, 1)
        self.line_cache_entry_flags = QtGui.QLineEdit(ChromePreviewDialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ebrima"))
        font.setPointSize(9)
        self.line_cache_entry_flags.setFont(font)
        self.line_cache_entry_flags.setObjectName(_fromUtf8("line_cache_entry_flags"))
        self.gridLayout_2.addWidget(self.line_cache_entry_flags, 8, 1, 1, 1)
        self.line_long_key_address = QtGui.QLineEdit(ChromePreviewDialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ebrima"))
        font.setPointSize(9)
        self.line_long_key_address.setFont(font)
        self.line_long_key_address.setObjectName(_fromUtf8("line_long_key_address"))
        self.gridLayout_2.addWidget(self.line_long_key_address, 7, 1, 1, 1)
        self.label_10 = QtGui.QLabel(ChromePreviewDialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ebrima"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 7, 0, 1, 1)
        self.label_12 = QtGui.QLabel(ChromePreviewDialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ebrima"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 9, 0, 1, 1)
        self.line_key_data = QtGui.QLineEdit(ChromePreviewDialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ebrima"))
        font.setPointSize(9)
        self.line_key_data.setFont(font)
        self.line_key_data.setObjectName(_fromUtf8("line_key_data"))
        self.gridLayout_2.addWidget(self.line_key_data, 9, 1, 1, 1)
        self.label_6 = QtGui.QLabel(ChromePreviewDialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ebrima"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_5 = QtGui.QLabel(ChromePreviewDialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ebrima"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.line_next_entry_address = QtGui.QLineEdit(ChromePreviewDialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ebrima"))
        font.setPointSize(9)
        self.line_next_entry_address.setFont(font)
        self.line_next_entry_address.setObjectName(_fromUtf8("line_next_entry_address"))
        self.gridLayout_2.addWidget(self.line_next_entry_address, 1, 1, 1, 1)
        self.line_entry_state = QtGui.QLineEdit(ChromePreviewDialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ebrima"))
        font.setPointSize(9)
        self.line_entry_state.setFont(font)
        self.line_entry_state.setObjectName(_fromUtf8("line_entry_state"))
        self.gridLayout_2.addWidget(self.line_entry_state, 4, 1, 1, 1)
        self.label_7 = QtGui.QLabel(ChromePreviewDialog)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ebrima"))
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 4, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 2, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 3, 0, 1, 1)

        self.retranslateUi(ChromePreviewDialog)
        QtCore.QMetaObject.connectSlotsByName(ChromePreviewDialog)

    def retranslateUi(self, ChromePreviewDialog):
        ChromePreviewDialog.setWindowTitle(_translate("ChromePreviewDialog", "Dialog", None))
        self.label.setText(_translate("ChromePreviewDialog", "Advanced info for entry:", None))
        self.label_8.setText(_translate("ChromePreviewDialog", "Creation time:", None))
        self.label_9.setText(_translate("ChromePreviewDialog", "Key data size (bytes):", None))
        self.label_3.setText(_translate("ChromePreviewDialog", "Next entry address:", None))
        self.label_2.setText(_translate("ChromePreviewDialog", "Key hash:", None))
        self.label_11.setText(_translate("ChromePreviewDialog", "Cache entry flags:", None))
        self.label_10.setText(_translate("ChromePreviewDialog", "Long key data address:", None))
        self.label_12.setText(_translate("ChromePreviewDialog", "Key data:", None))
        self.label_6.setText(_translate("ChromePreviewDialog", "Refetch count:", None))
        self.label_5.setText(_translate("ChromePreviewDialog", "Reuse count:", None))
        self.label_7.setText(_translate("ChromePreviewDialog", "Entry state:", None))

import icons_rc
